apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.27.0
  labels:
    cnpg.io/cluster: psql-cluster
    release: kube-prometheus-stack
  name: psql-cluster-podmonitor
  namespace: postgres
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
      name: ""
    port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: psql-cluster
      cnpg.io/podRole: instance
---
# Operator Metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-controller-manager
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
