apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-psql-cluster
  namespace: postgres
spec:
  cluster:
    name: psql-cluster
  instances: 2
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  type: rw
  serviceTemplate:
    metadata:
      labels:
        app: pooler
    spec:
      type: LoadBalancer
