apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pg-password-generator
  namespace: postgres
spec:
  length: 20
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
