apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes
          role: "openbao-readonly"
          mountPath: "kubernetes"
          serviceAccountRef:
            name: "openbao-sa"
